POST http://localhost:3001/api/blogs  
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRhcGlvc3UiLCJpZCI6MywiaWF0IjoxNzAwMjEzNDE3LCJleHAiOjE3MDAyOTk4MTcsImp0aSI6IjVhMDczNTI0LTE1MDYtNGZiMy04NjI3LWNlYWI5MDhmZjIxNSJ9.TvU8zFOCdIVwZRiS4oGpYISW5I7dFJ2OlKJkrhsLBXs

{
"title": "JV", "author": "JV", "url": "JV", "likes": 0, "year": 2023
}


