DELETE http://localhost:3001/api/blogs/2
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp2aWxodW5lIiwiaWQiOjEsImlhdCI6MTY5OTk1Njc0Mn0.5j4_wekXOSeSCvkPk8QC5zd0kLi8op2wA2v6D38y7kc
